### PR TITLE
Add pipeline support

### PR DESCRIPTION
**Pull request by maksonlee**

### CODE REVIEW

**Comment by mrooney** [comment]
Thanks, I think this is just what we need to ensure that Pipeline jobs (and their parallel tasks) are evenly distributed. @bstick12 if I build and verify this, would you be able to review and release it?

**Comment by bstick12** [comment]
@mrooney That sounds good. Apologies for not getting back sooner. 

Can you look at upgrading the latest parent version to 1.645

**Comment by benjaminfuchs** [comment]
Thanks for this fix! We suspected that it doesn't work properly for pipeline jobs but we haven't been sure. This PR was the proof. Can I help somehow to speed up it getting merged? @mrooney @bstick12

**Comment by bstick12** [comment]
@benjaminfuchs I've merged the request but the plugin build has been disabled by CloudBees. I've mailed support as I can unpause it. Once that is done I'll get a release out. Thanks for the testing.

**Comment by benjaminfuchs** [comment]
@bstick12 Any updates? If I can help let me know.

**Comment by bstick12** [comment]
@benjaminfuchs Just opened a PR to get added back as the developer so I can push a release https://github.com/jenkins-infra/repository-permissions-updater/pull/594

**Comment by bstick12** [comment]
@benjaminfuchs I've released 1.1.0 with the merged pipeline support.

**Comment by benjaminfuchs** [comment]
@bstick12 thanks!

**Comment by mrooney** [comment]
Thanks, we are using it and it seems helpful in basic scenarios! What I'm noticing however, is that it doesn't handle the case where pipelines allocate multiple nodes. For example:

```
parallel (
 unittests: { node {
    sh "sleep 300"

 }},
  uitests : { node {
    sh "sleep 300"
 }})
```

So these can end up on two executors on the same node, even when there are other nodes with 0 executors utilized. Is this intended and is there a way to hook into the allocation of nodes within a pipeline script?

**Comment by MrFishFinger** [comment]
i am in a similar situation to @mrooney , it seems like leastload is not being used with the parallel step unfortunately.

@bstick12 / @maksonlee  - do you know if parallel builds (within a jenkinsfile pipeline) should work with the plugin?
otherwise, do you have any pointers or tips on where we could start looking in the code, if we wanted to implement something like this?

**Pull request merged**
