### PR TITLE
Modernize plugin for 2020

### PR DESCRIPTION
**Pull request by basil**
This PR does some maintenance on this plugin to keep its build infrastructure up-to-date for 2020.

I started by updating `pom.xml` to follow [the latest archetype](https://github.com/jenkinsci/archetypes/blob/master/empty-plugin/src/main/resources/archetype-resources/pom.xml), notably a 4.1 parent POM. 4.x versions of the parent POM require a minimum Jenkins version of 2.164.x or later and Java 8 or later, so I updated `jenkins.version` and `java.level` accordingly. While I was here, I also updated Mockito to the latest version.

The Jenkins wiki has been deprecated, so I followed [the official instructions](https://www.jenkins.io/doc/developer/publishing/wiki-page/#migrating-from-wiki-to-github) to migrate wiki content to GitHub. This involved changing the URL in `pom.xml` and updating `README.md` to contain the old content from the wiki. I put the changelog in a separate `CHANGELOG.md` file following the common convention. `README.md` can be previewed [here](https://github.com/basil/leastload-plugin/tree/pom), and `CHANGELOG.md` can be previewed [here](https://github.com/basil/leastload-plugin/blob/pom/CHANGELOG.md).

The rest of the commits were just fixing IDE warnings after updating to the latest build infrastructure. These are all trivial changes and should be self-explanatory. I kept each commit separate and described the fix in each commit message.

### CODE REVIEW

**Comment by basil** [comment]
CC @bstick12

**Comment by basil** [comment]
I realized this plugin didn't have automated testing, so I also added an integration test that actually runs Jenkins and verifies the plugin works as expected.

**Comment by basil** [comment]
@bstick12 Here is a friendly reminder to please take a look at this.

**Comment by bstick12** [comment]
@basil Thanks for the PR - Apologies for the delay. Not to remember how to release it ;)

**Comment by basil** [comment]
@bstick12 Would you be interested in a co-maintainer for this plugin?

**Pull request merged**
