### PR TITLE
Routine updates

### PR DESCRIPTION
**Pull request by Vlatombe**
* Update parent POM (supercedes #11)
* Remove deprecated `Plugin` extension; use a `@Initializer` annotated static method instead.
* Add a few missing SpotBugs annotations
* Use standard class name for logger

This fixes a warning a startup due to the fact the latest release of the plugin is too old w.r.t to current toolchain

```
WARNING o.k.s.BytecodeReadingParanamer#lookupParameterNames: Looking up parameter names for public org.bstick12.jenkinsci.plugins.leastload.LeastLoadDisabledProperty(boolean); update plugin to a version created with a newer harness
```

### Submitter checklist
- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by Vlatombe** [comment]
cc @bstick12 since there is no reviewer defined for this repository.

**Comment by hashar** [comment]
Hello, I have recently adopted the plugin and had an interest in updating the toolchain.

Your commit 5ac09ef3c29a1eb4194eae6d70291eeb4e720956 mixes several fixes and I am not quite sure how to reproduce or validate each of them.  I have at least extracted the JenkinsFile configuration and updating the parent pom in a new pull request #14 which at least fixes CI.

From your commit message:

> * Update parent POM

Addressed by #14

> * Remove deprecated Plugin extension; use a https://github.com/Initializer annotated static method instead.

My guess is that it is why src/main/java/org/bstick12/jenkinsci/plugins/leastload/LeastLoadPlugin.java is removed. I would split in a standalone commit / pull request, but I don't know how to verify it.

> * Add a few missing SpotBugs annotations

I don't see failures in spotbugs with the 4.88 parent pom (spotbug 4.8.3.1)  The fixes should be made while enforcing spotbug as well https://www.jenkins.io/doc/developer/tutorial-improve/add-more-spotbugs-checks/ , but since all is green after #14 I am not sure anything has to be fixed.

> * Use standard class name for logger

This probably deserves a single commit/pull request as well. I'll try to do it :)

> This fixes a warning a startup due to the fact the latest release of the plugin is too old w.r.t to current toolchain
> ```
> WARNING o.k.s.BytecodeReadingParanamer#lookupParameterNames: Looking up parameter names for public org.bstick12.jenkinsci.plugins.leastload.LeastLoadDisabledProperty(boolean); update plugin to a version created with a newer harness
> ```
With #14 , I don't see the warning show up when using `mvn clean hpi:run`.

**Comment by Vlatombe** [comment]
Hi @hashar , thank you for adopting the plugin ! Feel free to salvage this PR as you see fit, I'm not waiting for any particular change.

**Comment by hashar** [comment]
@Vlatombe I will try to split it, there are interesting bits to keep around and I'll mark you as the author :]

**Pull request closed without merging**
